name: cd

on:
  push:
    branches: [main]

jobs:
  release:
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: release') }}"
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: nickdemianchuk/actions/.github/workflows/release.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
