name: cd

on:
  push:
    branches: [main]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: nickdemianchuk/actions/.github/workflows/release.yml@0.3.3
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
